TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += plc-ai.template
DB += plc-ao.template
DB += plc-bi.template
DB += plc-bo.template
DB += plc-first.template
DB += plc-fm.template
DB += plc-op-fs.template
DB += plc-pps-sh.template
DB += plc-pt.template
DB += plc-tc.template
DB += plc-va-gv.template
DB += plc-va-rly.template

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

